name: Kubescape
description: Run Kubescape scan
# author:

inputs:
  scanRepository:
      description: |
        yes or no input to scan the entire repository
      required: true
  accountGUID:
    description: |
      the github account id.
    required: false
  args:
    description: |
      Arguments to be passed to kubescape scan. The following
      arguments are supported - 
      -f, --format - Output format. Supported formats: 
                    "pretty-printer"/"json"/"junit"/"prometheus"
                    (default "pretty-printer")
      -o, --output - Output file. Print output to file and not stdout
      -s, --silent - Silent progress messages
      --verbose - Display all of the input resources and not only 
                  failed resources
      --logger - Logger level. Supported: debug/info/success/warning/
                 error/fatal (default "info")
    required: false
  threshold:
    description: |
      Failure threshold is the percent above which the command fails and 
      returns exit code 1 (default 0 i.e, action fails if any control fails)
    default: 0
    required: false
  files:
    description: |
      Path to the configuration yaml to scan
    required: false
  framework:
    description: |
      List of all frameworks to scan. Run kubescape list frameworks with 
      the Kubescape CLI to get a list of all frameworks. Either frameworks 
      have to be specified or controls.
    required: false
  control:
    description: |
      List of all controls to scan. Run kubescape list controls with the 
      Kubescape CLI to get a list of all controls. Either frameworks 
      have to be specified or controls.
    required: false
  exceptions:
    description: |
      Path to the json file containing exceptions.
    required: false
runs:
  using: docker
  image: Dockerfile
