name: Kubescape
description: Run Kubescape scan
inputs:
  failedThreshold:
    description: |
      Failure threshold is the percent above which the command fails and 
      returns exit code 1 (default 0 i.e, action fails if any control fails)
    required: false
  severityThreshold:
    description: |
      Severity threshold is the severity of a failed control at or above which
      the command terminates with an exit code 1 (default is "high", i.e. the
      action fails if any High severity control fails)
    required: false
    default: high
  files:
    description: |
      Path to the configuration yaml to scan
    required: false
  frameworks:
    description: |
      List of all frameworks to scan. Run kubescape list frameworks with 
      the Kubescape CLI to get a list of all frameworks. Either frameworks 
      have to be specified or controls.
    required: false
  controls:
    description: |
      List of all controls to scan. Run kubescape list controls with the 
      Kubescape CLI to get a list of all controls. Either frameworks 
      have to be specified or controls.
    required: false
  account:
    description: |
      Account ID for the Kubescape SaaS.
      Used for custom configuration, such as frameworks, control configuration, etc.
    required: false
  format:
    description: |
      Output format
      Run `kubescape scan -h` for listing supported formats
    required: false
    default: junit
runs:
  using: docker
  image: Dockerfile
  # image: docker://quay.io/kubescape/github-actions

