name: Kubescape scanning for misconfigurations
on: [push, pull_request]
jobs:
  kubescape-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: kubescape/github-action@main
      continue-on-error: true
      with:
        format: sarif
        outputFile: results.sarif
        # Kubescape cloud account ID
        account: ${{secrets.KUBESCAPE_ACCOUNT}}
        # # Optional - Scan a specific path. Default will scan all
        # files: "examples/*.yaml"
    - name: Upload Kubescape scan results to Github Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
